from datetime import datetime

now=datetime.now()
first_appointment=datetime(year=now.year,month=now.month,day=now.day,hour=9,minute=0,second=0)

Hospital1={101:{"clinic_id":1001,"clinic_name":"Cardiology","consultation_time":first_appointment},
           102:{"clinic_id":1001,"clinic_name":"Cardiology","consultation_time":first_appointment},
           103:{"clinic_id":1001,"clinic_name":"Cardiology","consultation_time":first_appointment},
           104:{"clinic_id":1002,"clinic_name":"Neurology","consultation_time":first_appointment},
           105:{"clinic_id":1002,"clinic_name":"Neurology","consultation_time":first_appointment},
           106:{"clinic_id":1003,"clinic_name":"Internal medicine","consultation_time":first_appointment},
           107:{"clinic_id":1003,"clinic_name":"Internal medicine","consultation_time":first_appointment},
           108:{"clinic_id":1003,"clinic_name":"Internal medicine","consultation_time":first_appointment},
           109:{"clinic_id":1003,"clinic_name":"Internal medicine","consultation_time":first_appointment},
           110:{"clinic_id":1004,"clinic_name":"Urology","consultation_time":first_appointment},
           111:{"clinic_id":1005,"clinic_name":"Dermatology","consultation_time":first_appointment},
           112:{"clinic_id":1005,"clinic_name":"Dermatology","consultation_time":first_appointment},
           113:{"clinic_id":1006,"clinic_name":"Physiotherapy","consultation_time":first_appointment},
           114:{"clinic_id":1006,"clinic_name":"Physiotherapy","consultation_time":first_appointment},
           115:{"clinic_id":1006,"clinic_name":"Physiotherapy","consultation_time":first_appointment},
           116:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           117:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           118:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           119:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           120:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           121:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           122:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           123:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           124:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           125:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           126:{"clinic_id":1008,"clinic_name":"Pediatrics","consultation_time":first_appointment},
           127:{"clinic_id":1008,"clinic_name":"Pediatrics","consultation_time":first_appointment},
           128:{"clinic_id":1008,"clinic_name":"Pediatrics","consultation_time":first_appointment},
           129:{"clinic_id":1008,"clinic_name":"Pediatrics","consultation_time":first_appointment},
           130:{"clinic_id":1008,"clinic_name":"Pediatrics","consultation_time":first_appointment},
           131:{"clinic_id":1008,"clinic_name":"Pediatrics","consultation_time":first_appointment},
           132:{"clinic_id":1008,"clinic_name":"Pediatrics","consultation_time":first_appointment}        
           }



Hospital2={201:{"clinic_id":2001,"clinic_name":"Cardiology","consultation_time":first_appointment},
           202:{"clinic_id":2001,"clinic_name":"Cardiology","consultation_time":first_appointment},
           203:{"clinic_id":2002,"clinic_name":"Neurology","consultation_time":first_appointment},
           204:{"clinic_id":2003,"clinic_name":"Internal medicine","consultation_time":first_appointment},
           205:{"clinic_id":2003,"clinic_name":"Internal medicine","consultation_time":first_appointment},
           206:{"clinic_id":2004,"clinic_name":"Urology","consultation_time":first_appointment},
           207:{"clinic_id":2005,"clinic_name":"Dermatology","consultation_time":first_appointment},
           208:{"clinic_id":2005,"clinic_name":"Dermatology","consultation_time":first_appointment},
           209:{"clinic_id":2006,"clinic_name":"Physiotherapy","consultation_time":first_appointment},
           210:{"clinic_id":2006,"clinic_name":"Physiotherapy","consultation_time":first_appointment},
           211:{"clinic_id":2006,"clinic_name":"Physiotherapy","consultation_time":first_appointment},
           212:{"clinic_id":2007,"clinic_name":"Medicine","consultation_time":first_appointment},
           213:{"clinic_id":2007,"clinic_name":"Medicine","consultation_time":first_appointment},
           214:{"clinic_id":2007,"clinic_name":"Medicine","consultation_time":first_appointment},
           215:{"clinic_id":2007,"clinic_name":"Medicine","consultation_time":first_appointment},
           216:{"clinic_id":2007,"clinic_name":"Medicine","consultation_time":first_appointment},
           217:{"clinic_id":2008,"clinic_name":"Pediatrics","consultation_time":first_appointment},
           218:{"clinic_id":2008,"clinic_name":"Pediatrics","consultation_time":first_appointment},
           219:{"clinic_id":2008,"clinic_name":"Pediatrics","consultation_time":first_appointment}       
           }


Hospital3={301:{"clinic_id":1001,"clinic_name":"Cardiology","consultation_time":first_appointment},
           302:{"clinic_id":1001,"clinic_name":"Cardiology","consultation_time":first_appointment},
           303:{"clinic_id":1002,"clinic_name":"Neurology","consultation_time":first_appointment},
           304:{"clinic_id":1002,"clinic_name":"Neurology","consultation_time":first_appointment},
           305:{"clinic_id":1002,"clinic_name":"Neurology","consultation_time":first_appointment},
           306:{"clinic_id":1003,"clinic_name":"Internal medicine","consultation_time":first_appointment},
           307:{"clinic_id":1003,"clinic_name":"Internal medicine","consultation_time":first_appointment},
           308:{"clinic_id":1003,"clinic_name":"Internal medicine","consultation_time":first_appointment},
           309:{"clinic_id":1003,"clinic_name":"Internal medicine","consultation_time":first_appointment},
           310:{"clinic_id":1004,"clinic_name":"Urology","consultation_time":first_appointment},
           311:{"clinic_id":1004,"clinic_name":"Urology","consultation_time":first_appointment},
           312:{"clinic_id":1005,"clinic_name":"Dermatology","consultation_time":first_appointment},
           313:{"clinic_id":1005,"clinic_name":"Dermatology","consultation_time":first_appointment},
           314:{"clinic_id":1006,"clinic_name":"Physiotherapy","consultation_time":first_appointment},
           315:{"clinic_id":1006,"clinic_name":"Physiotherapy","consultation_time":first_appointment},
           316:{"clinic_id":1006,"clinic_name":"Physiotherapy","consultation_time":first_appointment},
           317:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           318:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           319:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           320:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           321:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           322:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           323:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           324:{"clinic_id":1007,"clinic_name":"Medicine","consultation_time":first_appointment},
           325:{"clinic_id":1008,"clinic_name":"Pediatrics","consultation_time":first_appointment},
           326:{"clinic_id":1008,"clinic_name":"Pediatrics","consultation_time":first_appointment},
           327:{"clinic_id":1008,"clinic_name":"Pediatrics","consultation_time":first_appointment},
           328:{"clinic_id":1008,"clinic_name":"Pediatrics","consultation_time":first_appointment},
           329:{"clinic_id":1008,"clinic_name":"Pediatrics","consultation_time":first_appointment},
           330:{"clinic_id":1008,"clinic_name":"Pediatrics","consultation_time":first_appointment}, 
           331:{"clinic_id":1009,"clinic_name":"Dentis","consultation_time":first_appointment},
           332:{"clinic_id":1009,"clinic_name":"Dentis","consultation_time":first_appointment}, 
           333:{"clinic_id":1009,"clinic_name":"Dentis","consultation_time":first_appointment}, 
           334:{"clinic_id":1009,"clinic_name":"Dentis","consultation_time":first_appointment}       
           }